### Testing methodology for WY from 1982 data

library("rgdal")
library("rgeos")
library("maptools")
library("ggplot2")
library("plyr")
library("dplyr")
library("maps")
library("RColorBrewer")
library("lattice")
library("ncdf4")

setwd("C:/Users/lmitchis/Documents/R/usa_shapefiles")

usa48.df = read.csv("usa48.csv", header=TRUE)
global_lon_lat.df = read.csv("global_lon_lat.csv", header=TRUE)
rect.long.lat = read.table(file="rect-long-lat.txt", header=TRUE)
state.points.codes.df = read.csv(file="state.points.codes.csv", header=TRUE)

setwd("~/R/Temp data")
orldwide_t2m_1982 <- read.csv("worldwide_t2m_1982.csv", header=TRUE)
head(worldwide_t2m_1982[,1:8]) # DF is comes from NetCDF extraction script

# Using merge() to attach temp data to points with known states
usa.merge.1982 <- merge(state.points.codes.df, worldwide_t2m_1982, by=c("long","lat"))
head(usa.merge.1982[1:4,1:9])

# Extracts just WY points
WY.points <- usa.merge.1982[which(usa.merge.1982$STATE_ABBR=='WY'),]

#Extract just one WY point and doing statistics
WY.row <- WY.points[1,1:yrend]

# Sequence that for loops will run through
yrend <- length(WY.row)-1 # "-1" because last column was actually first day of 1983
x <- seq(from=9, to=yrend, by=2) # "by=2" so it gets every other column



### Point stats by day (dailystats.point)

## Daily mean - could easily get single row format for max and min with this same code

# Empty DF to bin values
dailymean.point <- data.frame(WY.row[1,1:8])
names(dailymean.point) <- names(WY.row[1:8])

# For loop that adds daily means in a new column each
for (day in x) { # "day" = col num in WY.row
  avg <- mean(c(WY.row[,day], WY.row[,day+1]))
  tempcol <- data.frame(avg)
  names(tempcol) <- colnames(WY.row[day])
  dailymean.point <- cbind(dailymean.point, tempcol)
}


## Daily mean, max, min for a single point (produces one long row of info)

# Mini DF just for first day since it only has one time rather than two
first.point <- data.frame(matrix(nrow=3, ncol=1))
row.names(first.point) <- c("mean", "max", "min")
colnames(first.point) <- colnames(WY.row[8])
first.point[1,] <- mean(WY.row[1,8])
first.point[2,] <- max(WY.row[1,8])
first.point[3,] <- min(WY.row[1,8])

# Setting up empty DF for all other days - columns go by date and rows are for mean, max, min
dailystats.point <- data.frame(matrix(nrow=3))
row.names(dailystats.point) <- c("mean", "max", "min")



# For loop that adds daily means in a new column each

for (day in x) { # "day" = col num in WY.row
  # Calculating stats
  avg <- mean(c(WY.row[,day], WY.row[,day+1]))
  max <- max(c(WY.row[,day], WY.row[,day+1]))
  min <- min(c(WY.row[,day], WY.row[,day+1]))
  
  # Putting stats into a new column
  tempcol <- data.frame(matrix(nrow=3, ncol=1))
  names(tempcol) <- colnames(WY.row[day])
  row.names(tempcol) <- c("mean", "max", "min")
  tempcol[1,] <- avg
  tempcol[2,] <- max
  tempcol[3,] <- min
  
  # Adding new column to full DF
  dailystats.point <- cbind(dailystats.point, tempcol)
}

# Removes first column which was blank
dailystats.point[1] <- NULL

# Adds in stats from first day ("first.point" DF)
dailystats.point <- cbind(first.point, dailystats.point)
# dailystats.point now has daily mean, max, min for a single point in WY



### Point stats by month (montlystats.point)

# Extracting out date columns
datelist <- names(WY.row[8:yrend])
datelist <- strsplit(datelist, "-")
months <- as.character(sapply(datelist, "[[", 2))

# Created copy of WY.row to experiment on; just of date columns
temp.row <- WY.row[8:yrend]

# Change column names to "01", "02", ect.
names(temp.row) <- months

# 2 col DF with month in one and temperature in other
temp.df <- data.frame(month=months, tmp=NA)
temp.df$tmp <- t(temp.row)

# Groups rows by common value in first col (month) and takes function of tmp values
m.mean <- tapply(temp.df$tmp, temp.df$month, FUN=mean)
m.max <- tapply(temp.df$tmp, temp.df$month, FUN=max)
m.min <- tapply(temp.df$tmp, temp.df$month, FUN=min)

# Putting it all into a DF
monthlystats.point <- data.frame(month=unique(sapply(datelist, "[[", 2)), d.mean=m.mean, d.max=m.max, d.min=m.min)
# monthlystats.point now has monthly stats for a singple point in a state of a given year



### State stats by day (dailystats.state)

## State mean by day

# Empty DF to bin values
dailymean.state <- data.frame(WY.points[1,1:8])
names(dailymean.state) <- names(WY.points[1:8])
# For loop that adds daily means in a new column each
for (day in x) { # "day" = col num in WY.points
  avg <- mean(c(WY.points[,day], WY.points[,day+1]))
  tempcol <- data.frame(avg)
  names(tempcol) <- colnames(WY.points[day])
  dailymean.state <- cbind(dailymean.state, tempcol)
}
# Comparing means generated by for loop vs. manually
mean(c(WY.points[,9], WY.points[,10])) #264.9046 - matches
mean(c(WY.points[,23], WY.points[,24])) #266.8789 - matches


## State stats by day

# Mini DF just for first day since it only has one time rather than two
first.state <- data.frame(matrix(nrow=3, ncol=1))
row.names(first.state) <- c("mean", "max", "min")
colnames(first.state) <- colnames(WY.points[8])
first.state[1,] <- mean(WY.points[,8])
first.state[2,] <- max(WY.points[,8])
first.state[3,] <- min(WY.points[,8])

# Setting up empty DF for all other days - columns go by date and rows are for mean, max, min
dailystats.state <- data.frame(matrix(nrow=3))
row.names(dailystats.state) <- c("mean", "max", "min")

# For loop that adds daily means in a new column each
for (day in x) { # "day" = col num in WY.points
  # Calculating stats
  avg <- mean(c(WY.points[,day], WY.points[,day+1]))
  max <- max(c(WY.points[,day], WY.points[,day+1]))
  min <- min(c(WY.points[,day], WY.points[,day+1]))
  
  # Putting stats into a new column
  tempcol <- data.frame(matrix(nrow=3, ncol=1))
  names(tempcol) <- colnames(WY.points[day])
  row.names(tempcol) <- c("mean", "max", "min")
  tempcol[1,] <- avg
  tempcol[2,] <- max
  tempcol[3,] <- min
  
  # Adding new column to full DF
  dailystats.state <- cbind(dailystats.state, tempcol)
}

# Removes first column which was blank
dailystats.state[1] <- NULL

# Adds in stats from first day ("first.state" DF)
dailystats.state <- cbind(first.state, dailystats.state)
# dailystats.state now has daily mean, max, min for all of WY state



### Point stats by month (montlystats.point)

# Extracting out date columns
datelist <- names(WY.row[8:yrend])
datelist <- strsplit(datelist, "-")
months <- as.character(sapply(datelist, "[[", 2))

# Created copy of WY.row to experiment on; just of date columns
temp.row <- WY.row[8:yrend]

# Change column names to "01", "02", ect.
names(temp.row) <- months

# 2 col DF with month in one and temperature in other
temp.df <- data.frame(month=months, tmp=NA)
temp.df$tmp <- t(temp.row)

# Groups rows by common value in first col (month) and takes function of tmp values
m.mean <- tapply(temp.df$tmp, temp.df$month, FUN=mean)
m.max <- tapply(temp.df$tmp, temp.df$month, FUN=max)
m.min <- tapply(temp.df$tmp, temp.df$month, FUN=min)

# Putting it all into a DF
monthlystats.point <- data.frame(month=unique(sapply(datelist, "[[", 2)), d.mean=m.mean, d.max=m.max, d.min=m.min)
# monthlystats.point now has monthly stats for a singple point in a state of a given year



### State stats by month (monthlystats.state)

# Extracting out date columns
datelist <- names(WY.points[8:yrend])
datelist <- strsplit(datelist, "-")
months <- as.character(sapply(datelist, "[[", 2))

# Created copy of WY.points to experiment on; just of date columns
temp.rows <- WY.points[,8:yrend]

# Change column names to "01", "02", ect.
names(temp.rows) <- months
# Columns are days, rows represent individual points

# 2 col DF with month in one and temperature in other
temp.df <- data.frame(month=months)
temp.df <- cbind(temp.df, t(temp.rows))
# Each row is one day; each column is one point

# Takes mean, max, min of each row, adds it on as a new column
temp.df$m.mean <- rowMeans(temp.df[,-1])
temp.df$m.max <- do.call(pmax, temp.df[,-1])
temp.df$m.min <- do.call(pmax, temp.df[,-1])

# Takes mean, max, min of each month (set of rows)
m.mean <- ddply(.data=temp.df,.(month),summarize,mean=mean(m.mean))
m.max <- ddply(.data=temp.df,.(month),summarize,m.max=max(m.max))
m.min <- ddply(.data=temp.df,.(month),summarize,m.min=min(m.min))

# Putting it all into a DF
monthlystats.state <- data.frame(month=unique(sapply(datelist, "[[", 2)), m.mean=m.mean$mean, m.max=m.max$m.max, m.min=m.min$m.min)
# monthlystats.state now has monthly stats for a whole state of a given year